### ISSUE TITLE
Will not build Cordova Example (VS Express 2013)

### ISSUE THREAD

**Issue by geoffdsims** [forcedotcom/SalesforceMobileSDK-WindowsSamples#22]
Attempting to learn to get authentication performed and I get the following errors after remapping the project CordovaApp.Windows(Windows 8.1) dependencies from your workstation mappings to mine after downloading:

1>------ Build started: Project: CordovaApp.Windows, Configuration: Debug Any CPU ------
1>C:\cordova-apps\SalesforceMobileSDK-WindowsSamples-master\Samples\UserList\plugins\com.salesforce\src\windows\src\Universal\Universal.csproj(175,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
1>C:\cordova-apps\SalesforceMobileSDK-WindowsSamples-master\Samples\UserList\plugins\com.salesforce\src\windows\src\Core\Core.csproj(113,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\Portable\v4.5\Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
1>C:\cordova-apps\SalesforceMobileSDK-WindowsSamples-master\Samples\UserList\plugins\com.salesforce\src\windows\src\Hybrid\Hybrid.csproj(144,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========

Also All project references (other than CordovaApp and Windows Library for JAvascript 2.0) do not exist when importing the project.

**Comment by kchitalia** [comment]
@geoffdsims I dont think this will work with VS 2013. Please try this with VS 2015. One more point to keep in mind, this sample has been built for Windows 10. Officially we dont support cordova for Windows 8.1

**Comment by geoffdsims** [comment]
Oh okay thanks for the reply i will try in vs2015.

I am trying to find something to view how to get user-agent flow login
method to work on a windows8/10 javascript store app.

The app i built currently uses oath username password flow authentication
and am trying to now shift to User-Agent Flow authentication (
https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_user_agent_flow.htm&language=en_US)
using javascript so SSO can be selected as needed.

We are in a contract with Salesforce reps and the Governing DOT agency for
the US and are trying to get this working on the 100s of windows8.1 surface
pros that the Salesforce sales team described as being supported.

This was the link our team was given as an example to use among a few
select others that no longer work so if you have any direction on how to
get the user-agent flow working in a javascript application I would
appreciate it in advance.

Thanks,

Geoff Sims

**Comment by kchitalia** [comment]
@geoffdsims Are you trying to build a cordova app? Or is it a native app using javascript?

**Comment by geoffdsims** [comment]
I have not been successful getting the user agent flow to work with either
approach.  I ideally would like it to be cordova.  However window.open
using the client id and redirect _ uri doesn't seem to work or call the
login.salesforce screen to login.

**Comment by helenren** [comment]
This sample has been gotten rid for lots of issues. We plan to develop a new one.
